# Generated by cucumber-sinatra. (2011-08-25 23:40:34 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'mytodo.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MyTodo

class MyTodoWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MyTodoWorld.new
end
